version: 2.1

orbs:
  common: radar/common@1.0
  node: radar/node@1.0

jobs:
  test:
    machine: true
    steps:
    - checkout
    - common/setup-gcp-gcr
    - common/install-docker-compose
    - node/install
    - run: 
        name: Setup Integration Environment
        command: |
          source ~/.bashrc
          scripts/simnet-setup.sh ci
    - run:
        name: Build Packages
        command: |
          source ~/.bashrc
          yarn build
    - run:
        name: Run Tests
        command: |
          source ~/.bashrc
          yarn test

workflows:
  default:
    jobs:
    - node/install-modules
    - node/lint:
        requires:
          - node/install-modules
    - test
